USE ROLE qa_service_ent_etl;
USE DATABASE WBMIQA_ORCHPOC_DB;

SET ENVIRONMENT = 'kent';
SET PICKUP_YEAR = 2025;
SET PICKUP_MONTH = 1;

SET PICKUP_MONTH_STR = (
    SELECT LPAD($PICKUP_MONTH, 2, '0')
);
SELECT $PICKUP_MONTH_STR;
SET TARGET_SCHEMA = CONCAT($ENVIRONMENT, '_MRT');

SET STAGE_NAME = CONCAT($TARGET_SCHEMA, '.EXPORT');
SET STAGE_URL = CONCAT('azure://wbcdaqpseudodlsa.blob.core.windows.net/outbound/', $ENVIRONMENT, '/EXPORT');

DROP STAGE IF EXISTS IDENTIFIER($STAGE_NAME);
CREATE STAGE IF NOT EXISTS IDENTIFIER($STAGE_NAME)
  URL = $STAGE_URL
  STORAGE_INTEGRATION = AZ_QA_PSEUDO_STORAGE_INTEGRATION
  DIRECTORY = (
    ENABLE = FALSE
    AUTO_REFRESH = FALSE
  );

SET OUTPUT_FILE_NAME = CONCAT('@',
  $STAGE_NAME,
  '/AGG_MONTHLY_ZONE_SUMMARY_',
  $PICKUP_YEAR,
  '_',
  $PICKUP_MONTH_STR,
  '.parquet'
);

SET SQL_QUERY = CONCAT(
  'COPY INTO ',
  $OUTPUT_FILE_NAME,
  ' FROM (SELECT * FROM ', $TARGET_SCHEMA, '.AGG_MONTHLY_ZONE_SUMMARY ',
  'WHERE PICKUP_YEAR = ', $PICKUP_YEAR,
  ' AND PICKUP_MONTH = ', $PICKUP_MONTH, ') ',
  'FILE_FORMAT = (TYPE = PARQUET) ',
  'SINGLE = TRUE OVERWRITE = TRUE'
);
EXECUTE IMMEDIATE $SQL_QUERY;
