USE ROLE QA_SYSADMIN;

SET ENVIRONMENT = 'kent';
SET TARGET_SCHEMA = CONCAT($ENVIRONMENT, '_EDL');

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($TARGET_SCHEMA);

SET TABLE_NAME = 'WBMIQA_ORCHPOC_DB.' || $TARGET_SCHEMA || '.YELLOW_TAXI_TRIPS';
SET BASE_LOCATION = CONCAT($ENVIRONMENT, '/yellow_taxi_trips/');

create or replace ICEBERG TABLE IDENTIFIER($TABLE_NAME)
 CATALOG = 'ADLS_WBCDAQPSEUDODLSA_CATALOG_DELTA'
 EXTERNAL_VOLUME = 'ADLS_WBCDAQPSEUDODLSA_ICEBERG' 
 BASE_LOCATION = $BASE_LOCATION;

SET TABLE_NAME = 'WBMIQA_ORCHPOC_DB.' || $TARGET_SCHEMA || '.TAXI_ZONE_LOOKUP';
SET BASE_LOCATION = CONCAT($ENVIRONMENT, '/taxi_zone_lookup/');
create or replace ICEBERG TABLE IDENTIFIER($TABLE_NAME)
 CATALOG = 'ADLS_WBCDAQPSEUDODLSA_CATALOG_DELTA'
 EXTERNAL_VOLUME = 'ADLS_WBCDAQPSEUDODLSA_ICEBERG' 
 BASE_LOCATION = $BASE_LOCATION;